import { PrismaClient } from '@prisma/client';

export default async function seedDepartments(prisma: PrismaClient) {
  await prisma.departmentTables.createMany({
    data: [
      {
        DEPARTMENT_NAME: 'Human Resources',
        CODE: 'HR',
        DESCRIPTION: 'Employee relations and talent management',
        OFFICER: 'Maria Santos',
        POSITION: 'HR Manager',
        ENTRY_DATE: new Date('2022-01-10'),
      },
      {
        DEPARTMENT_NAME: 'Finance',
        CODE: 'FIN',
        DESCRIPTION: 'Budgeting and financial operations',
        OFFICER: 'Juan Dela Cruz',
        POSITION: 'Finance Director',
        ENTRY_DATE: new Date('2021-11-05'),
      },
      {
        DEPARTMENT_NAME: 'Information Technology',
        CODE: 'IT',
        DESCRIPTION: 'Systems and infrastructure management',
        OFFICER: 'Kevin Reyes',
        POSITION: 'IT Head',
        ENTRY_DATE: new Date('2023-03-15'),
      },
      {
        DEPARTMENT_NAME: 'Procurement',
        CODE: 'PROC',
        DESCRIPTION: 'Purchasing and supplier coordination',
        OFFICER: 'Angela Cruz',
        POSITION: 'Procurement Officer',
        ENTRY_DATE: new Date('2022-06-20'),
      },
      {
        DEPARTMENT_NAME: 'Operations',
        CODE: 'OPS',
        DESCRIPTION: 'Daily operational management',
        OFFICER: 'Mark Bautista',
        POSITION: 'Operations Manager',
        ENTRY_DATE: new Date('2021-09-01'),
      },
      {
        DEPARTMENT_NAME: 'Logistics',
        CODE: 'LOG',
        DESCRIPTION: 'Asset and inventory movement',
        OFFICER: 'Paolo Mendoza',
        POSITION: 'Logistics Supervisor',
        ENTRY_DATE: new Date('2022-02-14'),
      },
      {
        DEPARTMENT_NAME: 'Maintenance',
        CODE: 'MAIN',
        DESCRIPTION: 'Equipment upkeep and repair',
        OFFICER: 'Ramon Flores',
        POSITION: 'Maintenance Chief',
        ENTRY_DATE: new Date('2020-08-10'),
      },
      {
        DEPARTMENT_NAME: 'Administration',
        CODE: 'ADMIN',
        DESCRIPTION: 'Office administration services',
        OFFICER: 'Liza Navarro',
        POSITION: 'Admin Officer',
        ENTRY_DATE: new Date('2023-01-25'),
      },
      {
        DEPARTMENT_NAME: 'Security',
        CODE: 'SEC',
        DESCRIPTION: 'Facility safety and protection',
        OFFICER: 'Carlos Rivera',
        POSITION: 'Security Head',
        ENTRY_DATE: new Date('2021-05-30'),
      },
      {
        DEPARTMENT_NAME: "City Accountant's Office",
        CODE: 'CAO',
        DESCRIPTION: 'City Finance and Accounting',
        OFFICER: 'Flabert Villasencio',
        POSITION: 'Acting CAO Head',
        ENTRY_DATE: new Date('2022-09-12'),
      },
      {
        DEPARTMENT_NAME: 'Quality Assurance',
        CODE: 'QA',
        DESCRIPTION: 'Process and standards monitoring',
        OFFICER: 'Erik Lim',
        POSITION: 'QA Manager',
        ENTRY_DATE: new Date('2023-04-05'),
      },
      {
        DEPARTMENT_NAME: 'Research and Development',
        CODE: 'RND',
        DESCRIPTION: 'Innovation and improvement initiatives',
        OFFICER: 'Sofia Tan',
        POSITION: 'R&D Director',
        ENTRY_DATE: new Date('2021-12-18'),
      },
      {
        DEPARTMENT_NAME: 'Legal',
        CODE: 'LEGAL',
        DESCRIPTION: 'Compliance and legal affairs',
        OFFICER: 'Victor Ong',
        POSITION: 'Legal Counsel',
        ENTRY_DATE: new Date('2020-10-22'),
      },
      {
        DEPARTMENT_NAME: 'Marketing',
        CODE: 'MKT',
        DESCRIPTION: 'Brand and promotions management',
        OFFICER: 'Chloe Perez',
        POSITION: 'Marketing Manager',
        ENTRY_DATE: new Date('2022-07-07'),
      },
      {
        DEPARTMENT_NAME: 'Training',
        CODE: 'TRN',
        DESCRIPTION: 'Staff development and learning',
        OFFICER: 'Daniel Aquino',
        POSITION: 'Training Coordinator',
        ENTRY_DATE: new Date('2023-02-11'),
      },
    ],
    skipDuplicates: true,
  });

  console.log('Seeding Department Completed');
}
