import { PrismaClient, Prisma } from '@prisma/client';

export default async function seedItems(prisma: PrismaClient) {
  const items = [
    {
      ITEM_NAME: 'Dell Latitude Laptop',
      DESCRIPTION: '14-inch business laptop',
      UNIT_VALUE: new Prisma.Decimal(45000.0),
      QUANTITY: 5,
      originalQuantity: 5,
      RECEIVED_AT: new Date('2024-01-10'),
      SERIAL_NO: 'LAP-001',
      DEPARTMENT_ID: 1,
      ADDED_BY: 10001,
      REMARKS: 'For office staff',
    },
    {
      ITEM_NAME: 'HP LaserJet Printer',
      DESCRIPTION: 'High-speed office printer',
      UNIT_VALUE: new Prisma.Decimal(18000.0),
      QUANTITY: 2,
      originalQuantity: 2,
      RECEIVED_AT: new Date('2024-02-15'),
      SERIAL_NO: 'PRN-002',
      DEPARTMENT_ID: 2,
      ADDED_BY: 10002,
      REMARKS: 'Shared equipment',
    },
    {
      ITEM_NAME: 'Office Chair',
      DESCRIPTION: 'Ergonomic swivel chair',
      UNIT_VALUE: new Prisma.Decimal(3500.0),
      QUANTITY: 20,
      originalQuantity: 20,
      RECEIVED_AT: new Date('2024-03-05'),
      SERIAL_NO: 'CHR-003',
      DEPARTMENT_ID: 1,
      ADDED_BY: 10003,
    },
    {
      ITEM_NAME: 'Desktop Computer',
      DESCRIPTION: 'Intel i7 workstation',
      UNIT_VALUE: new Prisma.Decimal(55000.0),
      QUANTITY: 4,
      originalQuantity: 4,
      RECEIVED_AT: new Date('2024-01-25'),
      SERIAL_NO: 'DTP-004',
      DEPARTMENT_ID: 3,
      ADDED_BY: 10004,
    },
    {
      ITEM_NAME: 'Projector',
      DESCRIPTION: 'Conference room projector',
      UNIT_VALUE: new Prisma.Decimal(22000.0),
      QUANTITY: 1,
      originalQuantity: 1,
      RECEIVED_AT: new Date('2024-04-12'),
      SERIAL_NO: 'PRJ-005',
      DEPARTMENT_ID: 2,
      ADDED_BY: 10005,
    },
    {
      ITEM_NAME: 'Filing Cabinet',
      DESCRIPTION: 'Steel 4-drawer cabinet',
      UNIT_VALUE: new Prisma.Decimal(8000.0),
      QUANTITY: 6,
      originalQuantity: 6,
      RECEIVED_AT: new Date('2024-02-01'),
      SERIAL_NO: 'CAB-006',
      DEPARTMENT_ID: 1,
      ADDED_BY: 10006,
    },
    {
      ITEM_NAME: 'Air Conditioner',
      DESCRIPTION: 'Split-type AC unit',
      UNIT_VALUE: new Prisma.Decimal(30000.0),
      QUANTITY: 2,
      originalQuantity: 2,
      RECEIVED_AT: new Date('2024-03-18'),
      SERIAL_NO: 'AC-007',
      DEPARTMENT_ID: 4,
      ADDED_BY: 10007,
    },
    {
      ITEM_NAME: 'Conference Table',
      DESCRIPTION: 'Large meeting table',
      UNIT_VALUE: new Prisma.Decimal(12000.0),
      QUANTITY: 1,
      originalQuantity: 1,
      RECEIVED_AT: new Date('2024-01-30'),
      SERIAL_NO: 'TAB-008',
      DEPARTMENT_ID: 3,
      ADDED_BY: 10008,
    },
    {
      ITEM_NAME: 'Router',
      DESCRIPTION: 'Enterprise network router',
      UNIT_VALUE: new Prisma.Decimal(9500.0),
      QUANTITY: 3,
      originalQuantity: 3,
      RECEIVED_AT: new Date('2024-04-01'),
      SERIAL_NO: 'RTR-009',
      DEPARTMENT_ID: 3,
      ADDED_BY: 10009,
    },
    {
      ITEM_NAME: 'External Hard Drive',
      DESCRIPTION: '2TB backup storage',
      UNIT_VALUE: new Prisma.Decimal(4500.0),
      QUANTITY: 10,
      originalQuantity: 10,
      RECEIVED_AT: new Date('2024-02-20'),
      SERIAL_NO: 'HDD-010',
      DEPARTMENT_ID: 3,
      ADDED_BY: 10010,
    },
  ];

  for (const item of items) {
    await prisma.items.upsert({
      where: { SERIAL_NO: item.SERIAL_NO! },
      update: {},
      create: { ...item, ADDED_BY: 1 },
    });
  }

  console.log('Seeding Items Successfully!\n');
}
